# Generated by Django 5.1.1 on 2025-11-15 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shopping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(fields=["user"], name="shopping_sh_user_id_5c6eb1_idx"),
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(
                fields=["recipe"], name="shopping_sh_recipe__f37dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(
                fields=["user", "added_at"], name="shopping_sh_user_id_f58377_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppinglist",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_user_recipe_cartitem"
            ),
        ),
    ]
