# Generated by Django 5.1.1 on 2025-11-15 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_in_recipes",
                to="recipes.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AddField(
            model_name="recipetag",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_tags",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddField(
            model_name="recipetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_in_recipes",
                to="recipes.tag",
                verbose_name="Тег",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeTag",
                to="recipes.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="uniq_recipe_ingredient"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 1)),
                name="recipeingredient_amount_ge_1",
            ),
        ),
        migrations.AddIndex(
            model_name="recipetag",
            index=models.Index(
                fields=["recipe"], name="recipes_rec_recipe__301a75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipetag",
            index=models.Index(fields=["tag"], name="recipes_rec_tag_id_bb695a_idx"),
        ),
        migrations.AddIndex(
            model_name="recipetag",
            index=models.Index(
                fields=["recipe", "tag"], name="recipes_rec_recipe__8cb209_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipetag",
            constraint=models.UniqueConstraint(
                fields=("recipe", "tag"), name="unique_recipe_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["author", "created_at"], name="recipes_rec_author__543c95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["name"], name="recipes_rec_name_891f25_idx"),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("cooking_time__gt", 0)),
                name="recipe_cooking_time_gt_0",
            ),
        ),
    ]
